import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import PageLayout from "@/components/PageLayout";
 
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth md:scroll-auto">
      <body
        className={`${inter.className} antialiased bg-stone-100 text-custom-gray-900`}
      >
        <PageLayout>
          {children}
        </PageLayout>
      </body>
    </html>
  );
}
